### ISSUE TITLE
Result of expression 'channel.toElement().firstChildElement' [undefined] is not a function.

### ISSUE THREAD

**Issue by etam** [reflexing/somafm#1]
Thank you for this plugin. It works fine in amarok 2.8.0 on openSUSE LEAP 42.2.

Unfortunately on openSUSE Tumbleweed (also in amarok 2.8.0) it doesn't work and shows the following error:
```
amarok: BEGIN: void Collections::ScriptableServiceQueryMaker::fetchAlbums() 
amarok:   [ScriptableServiceQueryMaker] parent id:  -1 
amarok:   BEGIN: void ScriptableServiceScript::slotPopulate(QString, int, int, QString, QString) 
amarok:     SCRIPT "SomaFM" :  "onPopulating(level = 1, callbackData = none, filter = )" 
amarok:     SCRIPT "SomaFM" :  "Populating channels (level 1)..." 
amarok:     SCRIPT "SomaFM" :  "channels == null, downloading channels..." 
amarok:     BEGIN: static QScriptValue Downloader::init(QScriptContext*, QScriptEngine*, bool) 
amarok:     END__: static QScriptValue Downloader::init(QScriptContext*, QScriptEngine*, bool) [Took: 0.001s] 
amarok:     SCRIPT "SomaFM" :  "Done populating channels (level 1)" 
amarok:   END__: void ScriptableServiceScript::slotPopulate(QString, int, int, QString, QString) [Took: 0.001s] 
amarok: END__: void Collections::ScriptableServiceQueryMaker::fetchAlbums() [Took: 0.001s] 
amarok: SCRIPT "SomaFM" :  "got 31 channels" 
amarok: SCRIPT "SomaFM" :  "parse station: 7soul" 
amarok: SCRIPT "SomaFM" :  "Caught error in function onChannelsXMLReceived: TypeError: Result of expression 'channel.toElement().firstChildElement' [undefined] is not a function." 
```
